name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run all tests
        run: npm run test:all
        
      - name: Build for production
        run: npm run build
        
      - name: Deploy to Replit
        run: |
          echo "🚀 Deployment triggered for Replit"
          echo "Build completed successfully"
          echo "Ready for manual deployment via Replit UI"
          
      - name: Create deployment notification
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "Version: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Timestamp: $(date)"
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "Check logs for details"